{{ if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloack-app.serviceAccountName" . }}
  labels:
    {{- include "keycloack-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
